### ISSUE TITLE
Spagetti Code

### ISSUE THREAD

**Issue by a2p1k02** [lupazapupa/GGS#2]
Sorry 🤌
I don't understood ur code 🤌
You 🤌 will 🤌 remake 🤌 this 🤌 shit 🤌
Mama 🤌mia🤌, 🤌pizza🤌, 🤌bugatti🤌, 🤌lamborghinni 🤌

Don't write in Pittonni, but write in Python 🤌🤌🤌🤌🤌🤌
P.S. 🤌🤌 🤌🤌   🤌🤌🤌🤌 🤌🤌🤌 🤌🤌🤌🤌🤌 🤌! 🤌.

**Comment by lupazapupa** [comment]
🍝
